server:
  port: 9090
security:
  oauth2:
    # oauth2 client配置，对应OAuth2ClientProperties类
    client:
      client-id: clientapp
      client-secret: 112233
    # oauth2 resource配置，对应ResourceServerProperties类
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/check_token
    # 访问令牌获取URL，自定义的
    access-token-uri: http://127.0.0.1:8080/oauth/token
